boostcampwm-2021/WEB01-NPE

- frontend/components/atoms/Chart/Chart.stories.tsx
- frontend/components/atoms/Chart/index.tsx
- frontend/components/atoms/Chart/styled.ts
- frontend/components/atoms/SearchBar/SearchBar.stories.tsx
- frontend/components/atoms/SearchBar/index.tsx
- frontend/components/atoms/SearchBar/styled.ts
#7 
#8 
검색바, 그래프 컴포넌트 만들기
스토리 추가
> Feature/#7#8 검색바 그래프 아토믹 컴포넌트만들기

- backend/src/graphql/index.ts
- backend/src/graphql/queries/QuestionQuery.ts
- backend/src/graphql/queries/QuestionsQuery.ts
- backend/src/graphql/services/PostService.ts
- backend/src/graphql/types/TagType.ts
#18 
- 질문글 검색 쿼리 거의 완료
- 현재 태그 타입 제외 모두 구현됨
> Feature/#18 백엔드 쿼리 마무리

- frontend/components/atoms/Indicator/Indicator.stories.tsx
- frontend/components/atoms/Indicator/index.tsx
- frontend/components/atoms/Indicator/styled.ts
#25 
- 라이브 스트리밍이 on, off인지를 알 수 있는 인디케이터
- 마우스를 hover하면 상태를 설명할 수 있도록 설정
- type을 boolean으로 넘겨서 on off 컴포넌트 지정 가능
- width, height를 설정 가능
> Feature/#25 atom 인디케이터 초록회색

- frontend/components/atoms/ContentText/ContentText.stories.tsx
- frontend/components/atoms/HeaderText/HeaderText.stories.tsx
- frontend/components/atoms/ProfileImage/ProfileImage.stories.tsx
- frontend/components/atoms/Text/Text.stories.tsx
- frontend/components/atoms/TitleText/TitleText.stories.tsx
#34
- 아톰 컴포넌트 스토리북 이름을 구조에 맞게 리팩토링 및 일부 수정
> refactor: [FE] 스토리북 이름 리팩토링

- frontend/components/molecules/profile-dropdown/profileDropdown.stories.tsx
#36 
ProfileDropDown 스토리 파일명 변경
> :truck: rename ProfileDropdown 스토리

- frontend/src/components/atoms/Button/index.tsx
- frontend/src/components/atoms/Button/styled.ts
- frontend/src/components/atoms/Indicator/index.tsx
- frontend/src/components/atoms/SideTag/index.tsx
- frontend/src/components/atoms/SideTag/sideTag.stories.tsx
- frontend/src/components/atoms/SideTag/styled.ts
- frontend/src/components/atoms/Switch/index.tsx
#51 
- style컴포넌트 import 방식 변경 {StyledButton} -> * as Styled
- props 인터페이스에서 함수 타입 변경 Function -> VoidFunction or (value:type) => void
- 함수 네이밍 수정 deleteHandler -> onDelete
- props 변수명 수정 type -> isOnline
> Fix/#51 멘토링회의 피드백 반영(Button, Switch, Indicator, SideTag)

- frontend/src/components/molecules/ProfileHeader/index.tsx
- frontend/src/components/molecules/ProfileHeader/styled.ts
- frontend/src/components/molecules/ProfileSummary/index.tsx
- frontend/src/components/molecules/ProfileSummary/styled.ts
#49
- 버튼을 링크(a)로 수정
- 그 외 스타일 일부 수정
> feat: [FE] 프로필 버튼을 링크로 수정

- frontend/src/components/atoms/SideTag/index.tsx
- frontend/src/components/atoms/SideTag/styled.ts
- frontend/src/components/atoms/TitleText/index.tsx
- frontend/src/components/molecules/TagSearch/index.tsx
- frontend/src/components/molecules/TagSearch/styled.ts
- frontend/src/components/organisms/SideBar/SideBar.stories.tsx
- frontend/src/components/organisms/SideBar/index.tsx
- frontend/src/components/organisms/SideBar/styled.ts
> Feature/#63 organism 사이드바

- frontend/src/components/atoms/index.ts
- frontend/src/components/organisms/SearchResult/SearchResult.stories.tsx
- frontend/src/components/organisms/SearchResult/index.tsx
- frontend/src/components/organisms/SearchResult/styled.ts
> Refactor/#73 organism 단일검색결과UI

- backend/src/graphql/services/PostService.ts
JOIN 을 사용한 방법이 아니라 버그 존재할 가능성 농후
#64
- 태그로 검색 기능
> Feature/Query Tag 구현

- backend/src/graphql/queries/UserQuery.ts
- backend/src/graphql/services/PostService.ts
X
- Questions 조회 시 createdAt 관련 오류 수정
> 🔨 Fix: console.log 삭제 및 id 기반으로 내림차순 정렬하도록 변경

- backend/src/graphql/index.ts
- backend/src/graphql/inputTypes/PostQuestionInput.ts
- backend/src/graphql/mutations/QuestionMutation.ts
- backend/src/graphql/queries/QuestionQuery.ts
- backend/src/graphql/queries/QuestionsQuery.ts
- backend/src/graphql/queries/TagQuery.ts
- backend/src/graphql/queries/TagsQuery.ts
- backend/src/graphql/queries/UserQuery.ts
- backend/src/graphql/services/PostService.ts
- backend/src/graphql/services/TagService.ts
- backend/src/graphql/types/PostAnswerType.ts
- backend/src/graphql/types/PostQuestionType.ts
- backend/src/graphql/types/TagType.ts
- backend/src/graphql/types/UserType.ts
#64 
- Tag 조회 쿼리 생성
- 태그 ID 혹은 Name 으로 나머지를 찾는 쿼리 구현
- 질문글 반환 오브젝트에 Tags 오브젝트 추가
- Grahpiql Docs 수정
> Feature/#64 Tag 관련 쿼리 및 Docs 수정

- backend/src/graphql/services/PostService.ts
- #84 
- Tag 다중검색 기능 비효율적인 로직 수정
- [관련글](https://dawitblog.tistory.com/176)
> Refactor/#84 Tag 검색 기능 쿼리 최적화

- frontend/src/components/molecules/QuestionTitle/QuestionTitle.stories.tsx
- frontend/src/components/molecules/QuestionTitle/index.tsx
- frontend/src/components/molecules/QuestionTitle/styled.ts
> :sparkles: feat: molecules QuestionTitle 추가

- backend/src/entities/PostAnswer.ts
- backend/src/entities/PostQuestion.ts
- backend/src/entities/PostQuestionHasTag.ts
- backend/src/graphql/index.ts
- backend/src/graphql/inputTypes/AnswerInput.ts
- backend/src/graphql/inputTypes/QuestionInput.ts
- backend/src/graphql/resolvers/AnswerResolver.ts
- backend/src/graphql/resolvers/QuestionResolver.ts
- backend/src/graphql/services/PostService.ts
- backend/src/graphql/services/TagService.ts
#99 
- 질문글 삭제
- 질문글 수정
- 답변글 작성
- WIP
> Feature/#99 Mutation 마무리

- frontend/src/components/atoms/Switch/index.tsx
- frontend/src/components/molecules/ProfileSummary/index.tsx
- frontend/src/components/organisms/SearchResult/index.tsx
- frontend/src/components/organisms/SideBar/index.tsx
#90 
#83
- Atom 리팩토링에 맞게 molecule 및 organisms 리팩토링
> Refactor/#90 molecule 및 organisms 리팩토링 구현

- frontend/src/pages/question/[id].tsx
- frontend/src/pages/tag/[name].tsx
#108 
질문조회 페이지
`/pages/question/[id].tsx` 파일 생성
ID가 3인 질문글의 타이틀을 클릭하면 `/question/3` 페이지로 라우팅
태그조회 페이지
`/pages/tag/[name].tsx` 파일 생성
name이 javascript인 태그를 클릭하면 `/tag/javascript` 페이지로 라우팅
> Feature/#108 다이나믹 라우팅 - Question, Tag 검색결과 페이지 레이아웃

- frontend/src/types/index.ts
> Feature/#110 프론트엔드 데이터 타입 정의

- frontend/src/components/organisms/Question/Question.stories.tsx
- frontend/src/components/organisms/Question/index.tsx
- frontend/src/components/organisms/Question/styled.ts
SearchResult->Question
#117 
Qusetion Organism 리팩토링
> :recycle: refactor: Organism-Question

- frontend/src/components/organisms/index.ts
> :label: feat: Add Organism export

- frontend/.gitignore
- frontend/package.json
- frontend/src/components/molecules/LoginModal/LoginModal.stories.tsx
- frontend/src/components/molecules/LoginModal/index.tsx
- frontend/src/components/organisms/Header/index.tsx
- frontend/src/pages/_app.tsx
- frontend/src/pages/_document.tsx
- frontend/src/pages/api/auth/[...nextauth].ts
#126
- next-auth 기반 로그인 로직을 구현했습니다.
- 로그인 안하고 질문하기 버튼 누르면 로그인 모달이 뜨도록 구현했습니다.
- _document 를 추가했습니다.
- 사용법 wiki 작성중,,,
> Feature/#126 로그인 로직 구현

- frontend/src/components/atoms/Chart/index.tsx
- frontend/src/components/atoms/Image/Image.stories.tsx
- frontend/src/components/atoms/Image/index.tsx
- frontend/src/components/molecules/ProfileDropdown/ProfileDropdown.stories.tsx
- frontend/src/components/molecules/ProfileDropdown/index.tsx
- frontend/src/components/molecules/ProfileHeader/styled.ts
- frontend/src/components/organisms/Header/Header.stories.tsx
- frontend/src/components/organisms/Header/index.tsx
- frontend/src/components/organisms/Header/styled.ts
- frontend/src/components/organisms/Question/index.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/profile/index.tsx
> Feature/#129 프로필 페이지 구현

- frontend/.babelrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/atoms/Button/index.tsx
- frontend/src/components/atoms/MDEditor/MdEditor.stories.tsx
- frontend/src/components/atoms/MDEditor/index.tsx
- frontend/src/components/atoms/MDViewer/MDViewer.stories.tsx
- frontend/src/components/atoms/MDViewer/index.tsx
- frontend/src/components/atoms/Switch/styled.ts
- frontend/src/components/atoms/TitleInput/Inputs.stories.tsx
- frontend/src/components/atoms/TitleInput/index.tsx
- frontend/src/components/atoms/TitleInput/styled.ts
- frontend/src/components/molecules/TagInput/TagInput.stories.tsx
- frontend/src/components/molecules/TagInput/index.tsx
- frontend/src/components/molecules/TagInput/styled.ts
- frontend/src/components/molecules/TagSearch/index.tsx
- frontend/src/components/molecules/TagSearch/styled.ts
- frontend/src/components/organisms/SideBar/styled.ts
- frontend/src/components/templates/ResisterQuestion/ResisterQuestion.stories.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
- frontend/src/components/templates/ResisterQuestion/styled.ts
- frontend/src/pages/MainPage/index.tsx
- frontend/src/pages/WritePage/index.tsx
- frontend/src/pages/_app.tsx
#106 
- 질문작성 페이지 구현
- 제목, 태그, 내용(마크다운), submit버튼 구현
> Feature/#106 질문작성페이지

- README.md
https://github.com/boostcampwm-2021/WEB01-NPE/tree/docs/README-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8
> Docs/readme 업데이트

- frontend/.babelrc
- frontend/next.config.js
- frontend/tsconfig.json
types, api alias
#133 
Add types, api alias
> :label: chore: update alias

- frontend/src/lib/index.ts
X
- api라우팅과 lib/api 함수를 분리
- Apollo Clinet import
- getQusetions 쿼리 수정
> [Fix]  Move pages/api/index.ts -> lib/api

- frontend/src/components/atoms/MDEditor/index.tsx
- frontend/src/components/atoms/MDViewer/index.tsx
> Fix/#135 toast UI 빌드에러

- frontend/src/lib/index.ts
> :sparkles: feat: Add API getOneQuestionByID

- backend/package-lock.json
- backend/package.json
- backend/src/App.ts
- frontend/src/components/atoms/Input/index.tsx
- frontend/src/components/molecules/TagSearch/index.tsx
- frontend/src/components/organisms/Header/index.tsx
- frontend/src/components/organisms/Header/styled.ts
- frontend/src/components/organisms/SideBar/index.tsx
- frontend/src/lib/index.ts
- frontend/src/pages/index.tsx
#136
- getStaticProps 사용해서 DB의 태그를 가져오도록 구현함
- forwardRef 로 input 아톰 컴포넌트 리팩토링
- 메인화면에서 검색바/태그 검색을 관리하도록 구현함
추후 검색결과 리스트 구현되면 검색 내용에 맞게 결과를 보여주는ㄴ 것을 구현하면 좋을 것 같습니다.
> Feature/#136 검색바 로직 구현하기

- backend/package.json
- backend/src/App.ts
- backend/src/entities/PostAnswer.ts
- backend/src/entities/Tag.ts
- backend/src/entities/User.ts
- backend/src/entities/UserHasTag.ts
- backend/src/graphql/services/PostService.ts
- backend/src/migrations/1636635559207-UserHasTagCountMigration.ts
- docker-compose.yaml
- frontend/package-lock.json
- frontend/src/lib/index.ts
- frontend/src/pages/profile/index.tsx
- frontend/src/types/index.ts
#147 
- 프로필 페이지 차트에 넣을 데이터 결정 필요
- 태그 집계 관련 테이블 마이그레이션
- 태그 집계 관련 Resolver 구현 필요
> Feature/#147 프로필 페이지 및 신규 태그 Resolver

- frontend/src/components/molecules/Vote/index.tsx
- frontend/src/components/molecules/Vote/styled.ts
- frontend/src/components/organisms/AnswerDetail/index.tsx
- frontend/src/components/organisms/DetailBody/index.tsx
- frontend/src/components/organisms/DetailBody/styled.ts
- frontend/src/components/organisms/QuestionDetail/index.tsx
- frontend/src/components/organisms/QuestionDetail/styled.ts
Vote, Detail
#156 
- `vote` molecules 추가
- `Detail` 관련 Organisms 추가
- 스토리북 미작성
- 이벤트 핸들러 구현예정
>  Feature/#156-Add-Mocule,Organisms

- frontend/src/components/molecules/ProfileSummary/index.tsx
> Refactoring] ProfileSummary 리팩토링

- frontend/src/components/atoms/MDEditor/MdEditor.stories.tsx
- frontend/src/components/atoms/MDEditor/index.tsx
- frontend/src/components/atoms/MDViewer/index.tsx
- frontend/src/components/molecules/ProfileSummary/styled.ts
- frontend/src/components/molecules/QuestionTitle/index.tsx
- frontend/src/components/molecules/QuestionTitle/styled.ts
- frontend/src/components/molecules/TagList/index.tsx
- frontend/src/components/molecules/TagList/styled.ts
- frontend/src/components/organisms/Question/Question.stories.tsx
- frontend/src/components/organisms/Question/index.tsx
- frontend/src/components/organisms/Question/styled.ts
- frontend/src/components/templates/QuestionList/QuestionList.stories.tsx
> Fix/#152 메인페이지 질문목록 UI수정

- frontend/src/pages/question/[id].tsx
> Feature/#145 질문조회 페이지 구현

- frontend/src/components/organisms/AnswerDetail/index.tsx
- frontend/src/components/organisms/AnswerDetail/styled.ts
- frontend/src/components/organisms/DetailBody/styled.ts
- frontend/src/components/organisms/QuestionDetail/index.tsx
- frontend/src/components/organisms/QuestionDetail/styled.ts
- frontend/src/pages/question/[id].tsx
> Design/#171 질문상세페이지

- frontend/src/components/atoms/MDEditor/WrappedEditor.tsx
- frontend/src/components/atoms/MDEditor/index.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
#174 
- WrappedMDEditor로 dynamic import 할 모듈 따로 분리
- ForwardRef로 ref 전달
> Fix/#174 MDEditor SSR 이슈 해결

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/templates/QuestionList/index.tsx
- frontend/src/components/templates/QuestionList/styled.ts
- frontend/src/pages/index.tsx
> Feature/#180 메인 무한스크롤링 구현

- frontend/src/components/atoms/TitleInput/Inputs.stories.tsx
- frontend/src/components/atoms/TitleInput/index.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
- frontend/src/lib/index.ts
#176
- 질문 작성 페이지 구현 (제목/실시간 공유)
-  마크다운 에디터 ref 이슈가 있음
> 질문 작성 로직 구현

- frontend/src/components/templates/QuestionList/styled.ts
- frontend/src/pages/profile/[userId].tsx
- 기존 프로필 유저 데이터를 세션에서 가져오는 방식에서 fetch를 통해 가져오는 방식으로 변경
- 채택 비율 도넛 그래프
> [FE/Feature] 프로필 페이지 Data fetch

- frontend/src/components/templates/ResisterQuestion/index.tsx
#184
window.alert 사용해서 제목 5자 이내시 경고를 보내도록 구현했습니다.
> 질문 작성 시 제목 5자 제한 validation

- frontend/src/components/organisms/SideBar/SideBar.stories.tsx
- frontend/src/components/organisms/SideBar/index.tsx
- frontend/src/lib/index.ts
- frontend/src/pages/index.tsx
#188
- 사이드바에서 스위치 누르면 필터링하도록 구현
- 무한스크롤시 검색바, 사이드바 필터링 적용이 안됨(아직 test 중이신꺼 같음)
- 스위치 색이 반대
> 실시간 공유 필터링 구현

- frontend/src/components/molecules/TagInput/TagInput.stories.tsx
- frontend/src/components/molecules/TagInput/index.tsx
- frontend/src/components/molecules/TagSearch/TagSearch.stories.tsx
- frontend/src/components/molecules/TagSearch/index.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
#200
- 질문 작성시 태그도 등록되도록 구현
- 기존에 태그를 클릭했을 때 제대로 동작하지 않던것 fix
- 중복 태그 등록 방지
> 질문 작성 페이지 태그 로직 구현

- backend/src/socket/index.ts
- frontend/src/components/organisms/LiveChat/LiveChat.stories.tsx
- frontend/src/components/organisms/LiveChat/index.tsx
- frontend/src/components/organisms/LiveChat/styled.ts
- frontend/src/components/templates/RealTimeModal/index.tsx
#197 
- 라이브 채팅 구현
- 유저 들어오고 나가는 socket 이벤트 구현
> Feature/#197 LiveChat 컴포넌트 구현

- frontend/src/components/organisms/AnswerRegister/index.tsx
> :sparkles: feat: [FE] 답변 작성 로직 마무리

- frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
- frontend/src/components/organisms/RealTimeEditor/editor.tsx
#218
- 코드 블록이 분리되서 탭으로 저장되도록 구현
- 아직은 자바스크립트만 지원
> 질문 코드별로 분리 구현

- frontend/src/components/molecules/TagInput/index.tsx
- frontend/src/components/organisms/SideBar/index.tsx
- frontend/src/lib/index.ts
- frontend/src/pages/index.tsx
#213 
(#211 브랜치에서 checkout 해서 작업했습니다)
무한스크롤시 필터링 한 값들이 적용되도록 구현
실시간 공유 필터링의 경우 false 일 때(실시간 공유 x 옵션일 때) 동작하지 않는 버그가 있습니다
> 무한스크롤시 검색 필터링 적용

- frontend/src/components/organisms/DetailBody/index.tsx
- frontend/src/components/organisms/DetailBody/styled.ts
- frontend/src/components/organisms/Question/index.tsx
> 질문, 질문조회 마크다운 뷰어 적용

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/molecules/Modal/index.tsx
- frontend/src/components/molecules/Modal/styled.ts
- frontend/src/components/molecules/index.ts
- frontend/src/components/organisms/AnswerRegister/index.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
- frontend/src/pages/_document.tsx
- frontend/src/pages/question/[id].tsx
#223 
- Modal을 따로 molecule컴포넌트로 뺌
- ReactDom.portal을 사용하여 바깥의 modal컴포넌트를 생성
> Feature/#223 에러 출력 모달창 구현

- frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
- frontend/src/components/organisms/RealTimeEditor/editor.tsx
- frontend/src/components/organisms/RealTimeEditor/styled.ts
#229
- 실시간 코드 공유 에디터 탬 추가/제거를 구현하였습니다.
- 모달창 나갈때 답변 등록과는 아직 연동 X
> 실시간 코드 공유 에디터 탬 추가/제거를 구현

- frontend/src/components/organisms/QuestionDetail/index.tsx
- frontend/src/components/organisms/QuestionDetail/styled.ts
> 질문글 삭제기능 추가

- backend/src/socket/index.ts
> :sparkles: feat: WebRTC 시그널링 서버 소켓

- frontend/src/pages/question/[id].tsx
>  질문조회페이지 SEO적용

- backend/src/socket/index.ts
- frontend/src/components/organisms/LiveChat/index.tsx
- frontend/src/components/organisms/LiveChat/styled.ts
#226 
- 실시간으로 사용자 출퇴장 확인할 수 있도록 구현
> Refactor/#226 채팅창 실시간 인원 표시

- frontend/src/components/templates/SEOHeader/index.tsx
- frontend/src/components/templates/index.ts
- frontend/src/pages/index.tsx
- frontend/src/pages/profile/[userId].tsx
- frontend/src/pages/question/[id].tsx
#253
- 메인 페이지, 프로필 페이지에 SEO 태그 추가
- SEOHeader 컴포넌트 구현 및 리팩토링
> title 및 SEO 태그 설정

- backend/src/services/UserService.ts
Closes #265 
- 회원가입 안돼서 활동 불가능하던 버그 수정
> [BE] Fix: 신규유저 회원가입 불가 버그 수정

- backend/src/socket/index.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/organisms/LiveAudioStream/Audio.tsx
- frontend/src/components/organisms/LiveAudioStream/index.tsx
- frontend/src/components/organisms/LiveAudioStream/styled.ts
> simple-peer webRTC 구현

- frontend/src/components/organisms/SideBar/styled.ts
> Fix/#264 사이드바 상단에 붙는 버그 Fix

- frontend/src/components/organisms/RealTimeEditor/styled.ts
- frontend/src/components/templates/RealTimeModal/index.tsx
- frontend/src/components/templates/RealTimeModal/styled.ts
> 실시간 모달 UI 개선

- frontend/src/components/organisms/Header/index.tsx
- frontend/src/components/organisms/RealTimeEditor/styled.ts
- frontend/src/pages/index.tsx
#258
- 로고 클릭시 검색바/사이드바 초기화
- 코드 공유 탭 스크롤 숨기기
> 페이지 로고 및 코드 공유 탭 개선

- backend/src/socket/index.ts
- frontend/src/components/organisms/AnswerRegister/index.tsx
- frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
- frontend/src/components/organisms/RealTimeEditor/editor.tsx
- frontend/src/components/organisms/RealTimeEditor/index.tsx
- frontend/src/components/templates/RealTimeModal/index.tsx
- frontend/src/pages/question/[id].tsx
#235
- 실시간 모달을 끌 때 작성한 답변이 순서대로 답변ㄴ 작성 에디터에 들어가도록 구현
- 코드 에디터가 모든 질문들에서 탭을 공유하던 문제를 수정
- 파이썬은 버그가 좀 있음(없앨까 생각중)
> 실시간 모달 닫을때 답변이 자동 입력되도록 구현

- README.md
- 뱃지의 웹사이트 주소를 nullpointerexception.ml 로 업데이트
> 뱃지의 웹사이트 주소를 nullpointerexception.ml 로 업데이트

- backend/src/resolvers/QuestionResolver.ts
- backend/src/resolvers/UserResolver.ts
- backend/src/services/PostService.ts
- backend/src/services/UserService.ts
> branch 278 -> 280

- backend/src/resolvers/QuestionResolver.ts
- backend/src/services/PostService.ts
- frontend/src/components/molecules/ExitCheckModalWapper/index.tsx
- frontend/src/components/templates/RealTimeModal/index.tsx
- frontend/src/lib/index.ts
> FE/BE Feature 질문자 퇴장시 실시간 공유 오프라인으로 전환

- backend/src/entities/PostQuestion.ts
- backend/src/errors/CommonError.ts
- backend/src/migrations/1637838136299-QuestionAdoptedColumn.ts
- backend/src/resolvers/AnswerResolver.ts
- backend/src/services/PostService.ts
- frontend/src/components/organisms/AnswerDetail/index.tsx
- frontend/src/components/organisms/DetailBody/index.tsx
- frontend/src/components/organisms/DetailBody/styled.ts
- frontend/src/lib/index.ts
- frontend/src/pages/question/[id].tsx
- frontend/src/types/index.ts
> 답변 채택 기능 구현

- frontend/src/components/organisms/AnswerRegister/index.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
- frontend/src/lib/index.ts
> API 호출 방식 통일

- frontend/src/components/organisms/DetailBody/index.tsx
#288 
- 이제 모든 사용자에게 채택 상태가 보이도록
-
> 채택 상태가 짊문자에게만 보이는 버그 수정

- frontend/src/components/organisms/AnswerRegister/index.tsx
- frontend/src/components/templates/ResisterQuestion/index.tsx
#295
- 글작성(짊문글/답변글) 10자보다 적을 때 모달 띄우기
- 모달창은 modal 컴포넌트를 활용
> 글작성 10자 제한

- frontend/src/types/index.ts
> :recycle: refactor: type extends

- frontend/src/components/organisms/SideBar/index.tsx
#307 
SideBar 중복 태그 추가 못하도록 수정
> [FE] SideBar 중복 태그 추가 못하도록 수정

- frontend/src/components/organisms/LiveChat/index.tsx
- frontend/src/components/organisms/LiveChat/styled.ts
#313 
- 새로운 채팅이 왔을 때 부드럽게 스크롤 아래로 가도록 기능 구현
> 채팅 스크롤 맨 아래로 가도록 수정

- frontend/src/lib/apolloClient.ts
- frontend/src/pages/api/auth/[...nextauth].ts
> jwt key 를 .env 로 수정

- frontend/src/components/organisms/Header/index.tsx
- frontend/src/components/organisms/Header/styled.ts
#317
- 창 크기가 줄어들어도 로고 크기는 변함없도록 구현
> 헤더 로고 크기 고정

- frontend/src/components/organisms/AnswerRegister/index.tsx
> 답변 작성 버그 수정

- frontend/src/components/molecules/Vote/styled.ts
- frontend/src/components/organisms/QuestionDetail/index.tsx
- frontend/src/components/organisms/QuestionDetail/styled.ts
- frontend/src/pages/profile/[userId].tsx
#322 
- 프로필 깃허브 버튼 hover될때 커서 포인터로 변경
- up & down 버튼도 커서 포인터로 변경
- 수정, 삭제 버튼 커서 포인터로 변경
> Fix/#322 커서 포인터로 변경

- backend/src/services/Tag/TagService.ts
- backend/src/services/Tag/TagServiceImpl.ts
- frontend/src/lib/index.ts
- frontend/src/pages/profile/[userId].tsx
- 태그 작성후 프로필에 들어가지지 않는 버그 수정
- 다만 여전히 태그가 달린 질문 삭제시 관련 태그 카운트가 삭제되지 않는 문제가 있습니다
> 태그 질문 작성 후 프로필 안들어가는 버그 수정

- backend/src/repositories/Question/QuestionRepositoryImpl.ts
- backend/src/resolvers/AnswerResolver.ts
- backend/src/resolvers/QuestionResolver.ts
- backend/src/services/Answer/AnswerService.ts
- backend/src/services/Answer/AnswerServiceImpl.ts
- backend/src/services/Question/QuestionService.ts
- backend/src/services/Question/QuestionServiceImpl.ts
- backend/test/unit/repository/AnswerRepo.test.ts
- backend/test/unit/repository/QuestionRepo.test.ts
- backend/test/unit/service/InjectRepo.ts
- backend/test/unit/service/QuestionService.test.ts
- 단위 테스트 계속 작성 중
- 질문/답변글 수정 메서드명 update -> modify로 변경
> Refactor/#330 단위 테스트 작성 및 일부 함수 이름 변경

- backend/test/integration/Answer.test.ts
- backend/test/integration/Question.test.ts
- backend/test/integration/User.test.ts
- backend/test/unit/service/AnswerService.test.ts
- backend/test/unit/service/QuestionService.test.ts
- 통합 테스트 단일화
- 단위 테스트 의존성 주입 beforeEach에서 처리
- AnswerService 단위 테스트 작성
> Refactor/#330 테스트 코드 추가 작성 및 리팩토링

- .github/workflows/Deploy.yml
- .github/workflows/Test.yml
- backend/.gitignore
- backend/package.json
- backend/test/integration/Answer.test.ts
- backend/test/integration/Question.test.ts
- backend/test/integration/mockdata/AnswerMock.ts
- backend/test/integration/mockdata/QuestionMock.ts
- backend/test/integration/mockdata/TagMock.ts
- backend/test/integration/mockdata/UserMock.ts
- backend/test/unit/repository/AnswerRepo.test.ts
- backend/test/unit/repository/QuestionRepo.test.ts
- backend/test/unit/repository/UserRepo.test.ts
- backend/test/unit/service/AnswerService.test.ts
- backend/test/unit/service/InjectRepo.ts
- backend/test/unit/service/QuestionService.test.ts
- backend/tsconfig.json
- 엔티티 구조 변경에 의해 실패하는 테스트들 수정
- PR 생성시 테스트 코드 수행
> Refactor/#330 깨진 테스트 수정 및 배포 스크립트 수정

- .github/workflows/Test.yml
> 테스트 스크립트 yaml 오타 수정

- .github/workflows/Test.yml
> 🚀 Chore: 테스트 스크립트 yaml 오타 수정

- .github/workflows/Deploy.yml
- backend/Dockerfile
- docker-compose.yaml
- 백엔드 pm2 적용
- Dockerfile Staging
> 🚀 Chore: CI/CD 개선 및 pm2 적용
